title: 
description: Jupyter Notebook scripts for the book "Performance Modeling and Analysis of Communication Networks" by Tran-Gia, P. & Hossfeld, T. (2021).
logo: performance_modeling.png
theme: jekyll-theme-minimal
