title: Performance Modeling
description: Jupyter Notebook scripts for the book Book "Performance Modeling and Analysis of Communication Networks" by Tran-Gia, P. & Hossfeld, T. (2021). Würzburg University Press. https://doi.org/10.25972/WUP-978-3-95826-153-2
theme: jekyll-theme-minimal
